#Por defecto spring brinda un tomcat embebido que hace que se despliegue en el puerto 8080

spring.datasource.url=jdbc:mysql://localhost:3306/inventory?useSSL=false&useLegacyDatetimeCode=false&serverTimeZonezone=UTCK
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource-driver-class-name=com.mysql.cj.jdbc.Driver

#ya no es necesaria en nuevas versiones
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#esto es para que automaticamente cuando creamos una nueva entidad y se lanza el proyecto se cree o se actualice
spring.jpa.hibernate.ddl-auto=update
#se utiliza principalmente para habilitar la impresión directa de consultas SQL en la consola
#spring.jpa.show-sql=true
#mujestra las consultas sql a nivel debug
#Muestra mas informacion y se puede establecer el nivel. Mayor nivel de detalle y control
loggin.level.org.hibernate.SQL=debug

### swagger configuration ###
#habilita la parte grafica de swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui-path=/swagger-ui.html


