#Por defecto spring brinda un tomcat embebido que hace que se despliegue en el puerto 8080

#me saltaba este error  "Public Key Retrieval is not allowed". con esta de abajo
#spring.datasource.url=jdbc:mysql://localhost:3306/inventory?useSSL=false&useLegacyDatetimeCode=false&serverTimeZonezone=UTCK
spring.datasource.url=jdbc:mysql://localhost:3306/inventory?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource-driver-class-name=com.mysql.cj.jdbc.Driver

#ya no es necesaria en nuevas versiones
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#esto es para que automaticamente cuando creamos una nueva entidad y se lanza el proyecto se cree o se actualice
spring.jpa.hibernate.ddl-auto=update
#se utiliza principalmente para habilitar la impresión directa de consultas SQL en la consola
#spring.jpa.show-sql=true
#mujestra las consultas sql a nivel debug
#Muestra mas informacion y se puede establecer el nivel. Mayor nivel de detalle y control
loggin.level.org.hibernate.SQL=debug

### swagger configuration ###

#habilita la parte grafica de swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui-path=/swagger-ui.html

### Srping por defecto soporta archivos de 1 mb maximo ###

#Define el tamaño máximo permitido para cada archivo cargado en una solicitud multipart. Si un archivo excede este límite, se generará un error.
spring.servlet.multipart.max-file-size=3MB
# Define el tamaño máximo permitido para toda la solicitud HTTP multipart. Esto incluye el tamaño total de todos los archivos cargados y otros datos multipart. Si la solicitud excede este límite, se generará un error.
spring.servlet.multipart.max-request-size=3MB


